version: '3.8'

services:
  api:
    container_name: savvy_backend
    build: apps/api
    volumes:
      - ./apps/api:/app
    ports:
      - "3333:3333"
    depends_on:
      - db
      - redis

  web:
    container_name: savvy_frontend
    build: apps/web
    volumes:
      - ./apps/web:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
  
  db:
    container_name: savvy_postgres
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    container_name: savvy_redis
    image: redis:8.0.3
    ports:
      - "6379:6379"

volumes:
  pgdata:
