version: '3.8'

services:
  api:
    build: apps/api
    volumes:
      - ./apps/api:/app
    ports:
      - "3333:3333"
    depends_on:
      - db
      - redis
    networks:
      - savvy_network

  web:
    build: apps/web
    volumes:
      - ./apps/web:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - savvy_network
  
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - savvy_network
  
  redis:
    image: redis:8.0.3
    ports:
      - "6379:6379"
    networks:
      - savvy_network

volumes:
  pgdata:

networks:
  savvy_network:
    driver: bridge
