version: '3.8'

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  redis:
    image: redis:8.0.3
    ports:
      - "6379:6379"

volumes:
  pgdata: